### ISSUE TITLE
Dedicated nodes: difficult to read the hint on the price

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1478]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/ec45d6d3-a559-4924-903d-a5a37825053d)

**Comment by ehab-hassan** [comment]
Fixed tooltip at development__313_farm_enhancement branch ll create PR soon
![Untitled-1](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/10a8c8df-3c27-46aa-ac64-13987af617a4)

**Comment by zaelgohary** [comment]
Tooltip is not fixed yet.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/6b4c5edd-5c94-4fb1-9056-5faa6789b124)

**Comment by ehab-hassan** [comment]
it seems my code was overridden :)
https://github.com/threefoldtech/tfgrid-sdk-ts/commit/6819bfbc2c9e70e12eb4030fde22f28693fa7bf1 
created new PR
https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1634

**Comment by A-Harby** [comment]
Verified,
- Devnet
- 13a87cf
- [TC2219 - List Dedicated Nodes](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150428)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1fe99ec9-3135-4888-ba69-21136bc6c2d9)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/9447d2ff-59aa-4b0d-8bc6-ac59b038784c)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 2.3.0-alpha3
