### ISSUE TITLE
Both dashboards are inaccessible - Cameron 

### ISSUE THREAD

**Issue by amandacaster** [threefoldtech/tfgrid-sdk-ts#1583]
### Dashboard inaccessible 

Both the new and the old dashboards are throwing errors to log in. 

The New dashboard is not accepting the TF Chain secret key as the mnemonics 

![photo_2023-12-05_16-44-05](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/88147124/d67bec39-e3fb-4e59-a4b4-094bd81ac622)
 After accepting the terms and conditions, the old dashboard throws a reject message (see bottom right corner).
 ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/88147124/57da63e3-0669-42d1-b7a3-b2ab70a183f4)

**Comment by ramezsaeed** [comment]
Reproduced on the old dashboard
and have the same rejected pop up down right corner

![Screenshot from 2023-12-06 16-55-58](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/aa57b3a0-0fff-4a57-9669-8ffcf09ab47c)

**Comment by A-Harby** [comment]
Fixed,

I tried on Qanet and Testnet, and both worked fine and have been for a while.

And same on Devnet with the new Dashboard UI, 2d54818.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0862ff49-66ee-4c6a-9600-1d59f3b21b6b)

[TC2118 - Create a new twin](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4150327)

**Comment by amandacaster** [comment]
Hey @A-Harby! Just asked @Cameron1986labeyrie to check and see if he can log into his dashboard, but it is still not accepting the  Hex. Can he try again later or does he have to for the 3.13 release for the fix to come to play
![photo_2023-12-08_15-36-17](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/88147124/66543b77-ff66-4311-b2f7-ebc4258f97fc)

**Comment by A-Harby** [comment]
Hi @amandacaster, Yes indeed, the hex isn't yet released yet on the Mainnet and it shouldn't be even released on 3.12 but rather on 3.13

**Comment by amandacaster** [comment]
> Hi @amandacaster, Yes indeed, the hex isn't yet released yet on the Mainnet and it shouldn't be even released on 3.12 but rather on 3.13

What about the old Dashboard can that error be fixed now?

**Comment by A-Harby** [comment]
> What about the old Dashboard can that error be fixed now?

I don't think so because it's not a bug we are fixing, so we can't do a hotfix, but rather a new feature that needs some development and testing to be released.

**Comment by amandacaster** [comment]
> > What about the old Dashboard can that error be fixed now?
> 
> I don't think so because it's not a bug we are fixing, so we can't do a hotfix, but rather a new feature that needs some development and testing to be released.

Thank you for the update @A-Harby!

**Comment by ramezsaeed** [comment]
will be released in 3.13
cannot hot fix it in the current release on Mainnet

**Comment by amandacaster** [comment]
> will be released in 3.13 cannot hot fix it in the current release on Mainnet

Thanks for confirming @ramezsaeed.

**Comment by xmonader** [comment]
This is not a confirmation from development team. old.dashboard.grid.tf works with the polkadot extensions with whatever it supports including hex seeds. forum post https://forum.threefold.io/t/old-dashboard-grid-tf-is-deployed-for-farmers-using-hex-based-secrets/4081	

@amandacaster please try using https://old.dashboard.grid.tf with an activated account with hex seed 

@ramezsaeed please make sure it's tested and if it's not working as expected please escalate, if so it's going to be hotfixed for 3.11.

**Comment by xmonader** [comment]
as for the https://dashboard.grid.tf , creation on the new dashboard works

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/f78535a7-b8d2-41c7-8d0c-06ad5cc6bf6b)

and twin activated 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/ce922946-3ec7-41ee-9a9a-8e9af9cb77ee)


the old.dashboard is meant for people with existing hex seeds and it should work.

**Comment by amandacaster** [comment]
Hey @xmonader, I tried the following  2 test attempts on the old dashboard https://old.dashboard.grid.tf/

1. I tried importing the account to Polkadot using the Hex, although the account shows up on the dashboard when you try to Accept Terms and Conditions it gives us a rejection as you see in the screenshot below. 

![photo_2023-12-12_12-38-35](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/88147124/4b91e3d0-7007-4530-ab81-b69fbf6c364c)

2. I tried creating a new account and again although the account shows up on the dashboard when you try to Accept Terms and Conditions it gives us a rejection as you see in the screenshot above. 

Coming to the new dashboard https://dashboard.grid.tf/ Creation of a new account works for us as well.

**Comment by AhmedHanafy725** [comment]
I can confirm that the old.dashboard.grid.tf has an issue in creating a new account, and a newer version will be deployed today to solve this issue. @amandacaster I'll let you know once the new version is deployed to test it again.

**Comment by amandacaster** [comment]
> I can confirm that the old.dashboard.grid.tf has an issue in creating a new account, and a newer version will be deployed today to solve this issue. @amandacaster I'll let you know once the new version is deployed to test it again.

Sounds great @A-Harby, thank you.

**Comment by AhmedHanafy725** [comment]
@amandacaster v2.1.0-rc2 has been deployed

**Comment by amandacaster** [comment]
> @amandacaster v2.1.0-rc2 has been deployed

Thanks, @AhmedHanafy725! Will try from our end and get back to you.

**Comment by amandacaster** [comment]
> > @amandacaster v2.1.0-rc2 has been deployed
> 
> Thanks, @AhmedHanafy725! Will try from our end and get back to you.



> > @amandacaster v2.1.0-rc2 has been deployed
> 
> Thanks, @AhmedHanafy725! Will try from our end and get back to you.

Checked and it is all good from our end, thank you team.
