### ISSUE TITLE
Tables shows NAN when no data is available

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1616]
### Description

Devnet, 2d54818.

All the tables, when they don't have data available on them, show 0-NAN of NAN, and the navigation page is enabled.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/85f268e4-789f-488a-ac51-9a7ff4f809d6)

**Comment by maayarosama** [comment]
Not reproducible 
![photo_2023-12-11_15-00-23](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/66883096/ae3e7c96-33dc-464f-b49a-ff98dbff8e43)

**Comment by A-Harby** [comment]
It happens when the request to get farms or nodes fail from a network issue and it should be fixed on https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1599

**Comment by khaledyoussef24** [comment]
tried to produce this issue same time but still Not reproducible
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ce02e4aa-cc5c-4ff4-84de-dd60593d1aae)

**Comment by ramezsaeed** [comment]
Cannot reproduce.
please re-open if happen again.
