### ISSUE TITLE
Unclear error in the deployment list while deleting a full vm

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#400]
### Description

The following error appeared in the deployment list after deleting a full vm deployment, the deployment was deleted successfully with all of its contracts

```
TypeError: Cannot read properties of undefined (reading 'filter')
```

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/e73e897d-2cae-4d9c-918f-226a15ad09c6)

and the following error appeared in the console.

```
TypeError: Cannot read properties of undefined (reading 'publicIP')
    at deployedlist.wc.js:8:98887
```

**Comment by mohamedamer453** [comment]
Also happened in casperlabs

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/c30ab9d5-5ec7-430f-86f8-4e334fa47bfa)

**Comment by Mahmoud-Emad** [comment]
I think it's a not valid issue because I just deployed the two instances and all of them passed smoothly 


https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/9ee8e1a8-10a8-4e6d-9f52-a1100e6ab911

**Comment by mohamedamer453** [comment]
@Mahmoud-Emad The issue was mainly in the old playground and it still happens when you delete any deployment.

It also happened with me in the new playground during Rollback of any deployment where the mentioned error appears in the console and the deployment gets stuck at `Rolling back deployments` forever.

**Comment by Mahmoud-Emad** [comment]
I just tested it in the new playground, can you please re-test it in the new playground?

also about the old one @xmonader  do we need to fix any issues there?

**Comment by AhmedHanafy725** [comment]
after checking the logs, found that this error happens after deleting any machine when the kvstore is used. but the playground is dropping the error

**Comment by AhmedHanafy725** [comment]
A fix has been merged into the grid client, but it will be deployed with the coming release

**Comment by mohamedamer453** [comment]
Verified.

The issue was fixed both on the old weblets.

[Screencast from 21-06-23 11:57:43.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/eba43a58-7b0e-4f51-a6cb-aa5b96d7fe58)

and in the playground i tried the same flow locally and did the same thing to rollback the deployment and it was successful and the rollback was completed without any issues.


https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/626605f4-88e9-4a0c-b3bb-574e459cf008
